---
title: "Class17"
author: "May Alsoufi (PID: A17423250)"
format: pdf
---

```{r}
files <- c(
"Data/SRR2156848_quant/abundance.tsv",
"Data/SRR2156849_quant/abundance.tsv",
"Data/SRR2156850_quant/abundance.tsv",
"Data/SRR2156851_quant/abundance.tsv"
)
```

```{r}
library(tximport)
library(ggplot2)
library(rhdf5)

folders <- dir("Data", pattern="SRR21568")
folders <- file.path("Data", folders)

samples <- sub("_quant", "", basename(folders))
files <- file.path(folders, "abundance.h5")
names(files) <- samples

txi.kallisto <- tximport(files, type="kallisto", txOut=TRUE)

to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]

keep2 <- apply(kset.nonzero,1,sd) > 0
x <- kset.nonzero[keep2,]

pca <- prcomp(t(x), scale=TRUE)

pca_df <- data.frame(pca$x)
pca_df$sample <- rownames(pca_df)

pca_df$group <- c("control","control","CRISPR","CRISPR")
```

```{r}
head(txi.kallisto$counts)
```

```{r}
colSums(txi.kallisto$counts)
```

```{r}
sum(rowSums(txi.kallisto$counts) > 0)
```

```{r}
ggplot(pca_df, aes(PC1, PC2, color=group, label=sample)) +
  geom_point(size=4) +
  geom_text(vjust=-1) +
  theme_minimal()
```

```{r}
ggplot(pca_df, aes(PC1, PC3, color=group, label=sample)) +
  geom_point(size=4) +
  geom_text(vjust=-1) +
  theme_minimal()
```

```{r}
ggplot(pca_df, aes(PC2, PC3, color=group, label=sample)) +
  geom_point(size=4) +
  geom_text(vjust=-1) +
  theme_minimal()
```

